{
 "title": "AWS Cost Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "awsAccount",
    "label": "awsAccount",
    "query": {
     "query": "label_values(aws_daily_cost_usd,Publisher)"
    }
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(aws_daily_cost_usd{Publisher=\"$awsAccount\"},RegionName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "备注", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 1 },
   "options": {
    "content": "AWS账号 ID | 项目名称\n---|---\n618443055614 | Transfer Production, 1Token\n711891019284 | CTA Staging, Transfer Staging\n733691812639 | 自营生产, CTA生产\n373106173498 | legacy账号, mm3.0及历史服务\n---\n> 柱状图下方显示日期非账单真是日期, 由于aws账单当日或当月账单展示不完整, 所以日账单取2日前的数据,月账单去上个月账单.\n* 日账单: “2025-08-28” -->> “2025-08-26”\n* 月账单: “2025-08” -->> “2025-07”"
   }
  },
  {
   "title": "月账单",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "所有账号月账单",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by(EnvironmentName, Monthly) (max without (instance, pod) (max_over_time(aws_monthly_cost_usage_usd[24h] offset -24h)))",
     "legendFormat": "{{EnvironmentName}},{{Monthly}}月份"
    }
   ]
  },
  {
   "title": "所有账号月账单",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by(EnvironmentName, Monthly, ServiceName) (max without (instance, pod) (max_over_time(aws_monthly_cost_usage_usd{Publisher=\"$awsAccount\"}[24h] offset -24h)))",
     "legendFormat": "{{EnvironmentName}},{{Monthly}}月份"
    }
   ]
  },
  { "title": "日账单", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "所有账号日消费",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (EnvironmentName) (max without (instance, pod) (max_over_time(aws_daily_cost_usd[24h] offset -24h)))",
     "legendFormat": "{{EnvironmentName}}: {{ServiceName}}"
    }
   ]
  },
  {
   "title": "指定账号服务费用分类",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (EnvironmentName,ServiceName) (max without (instance, pod) (max_over_time(aws_daily_cost_usd{Publisher=\"$awsAccount\"}[24h] offset -24h)))",
     "legendFormat": "{{EnvironmentName}}: {{ServiceName}}"
    }
   ]
  },
  {
   "title": "指定账号分类费用 by Tag",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by(RegionName, TagByProject) (max without (instance, pod) (max without (instance, pod) (max_over_time(aws_daily_cost_by_tag_project{Publisher=\"$awsAccount\",RegionName=~\"$region\"}[24h] offset -24h))))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}