{
 "title": "AWS Cost Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "awsAccount",
    "label": "awsAccount",
    "query": {
     "query": "label_values(aws_daily_cost_usd,Publisher)"
    }
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(aws_daily_cost_usd{Publisher=\"$awsAccount\"},RegionName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AWS Total Costs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (max_over_time(aws_daily_cost_usd[24h] offset -24h))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Costs per AWS Account",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (Publisher) (max_over_time(aws_daily_cost_usd[24h] offset -24h))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Costs per AWS Region",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (RegionName) (max without (instance, pod) (max_over_time(aws_daily_cost_usd[24h] offset -24h)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Costs per Account",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (ProjectName) (max without (instance, pod) (max_over_time(aws_daily_cost_usd[24h] offset -24h)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Costs per Account",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (RegionName, TagByProject) (max without (instance, pod) (max_over_time(aws_daily_cost_usd_by_tag_region_project[24h] offset -24h)))",
     "legendFormat": "{{RegionName}}: {{TagByProject}}"
    }
   ]
  },
  { "title": "Daily Costs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Costs per AWS Account and ServiceName",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (Publisher,ServiceName) (max without (instance, pod) (max_over_time(aws_daily_cost_usd{Publisher=\"$awsAccount\"}[24h] offset -24h)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Costs per AWS Account by Project",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by(Publisher, RegionName, TagByProject) (max without (instance, pod) (max without (instance, pod) (max_over_time(aws_daily_cost_usd_by_tag_region_project{Publisher=\"$awsAccount\",RegionName=~\"$region\"}[24h] offset -24h))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Costs per AWS Account by Project and Service",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by(Publisher, TagByProject, TagByService) (max without (instance, pod) (max_over_time(aws_daily_cost_usd_by_tag_project_service{Publisher=\"$awsAccount\"}[24h] offset -24h)))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}