apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cost-exporter
  labels:
    app.kubernetes.io/name: aws-cost-exporter
    app.kubernetes.io/part-of: finops
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "v1.0.11"
    app.kubernetes.io/language: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-cost-exporter
      app.kubernetes.io/part-of: finops
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aws-cost-exporter
        app.kubernetes.io/part-of: finops
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: aws-cost-exporter
          image: "opensourceelectrolux/aws-cost-exporter:v1.0.11"
          command: [ "python", "main.py", "-c", "/exporter_config.yaml" ]
          imagePullPolicy: Always
          env:
          - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-cost-exporter
                key: aws_access_key
          - name: AWS_ACCESS_SECRET
            valueFrom:
              secretKeyRef:
                name: aws-cost-exporter
                key: aws_access_secret
          ports:
            - containerPort: 9090
              name: metrics
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: metrics
            failureThreshold: 10
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: metrics
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 300Mi
          volumeMounts:
          - name: config-volume
            mountPath: /exporter_config.yaml
            subPath: exporter_config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: aws-cost-exporter-config
