apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::711891019284:role/CostExporterRoleClusterCtaStaging
  name: aws-cost-exporter
